language: php

php:
    - 5.3.0
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer install

script: vendor/bin/phpspec run -c phpspec-clover.yml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage/clover.xml
